# Generated by Django 4.1 on 2024-11-10 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0002_rename_product_producto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=250)),
                ('ciudad', models.CharField(max_length=100)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('pagado', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.AddIndex(
            model_name='orden',
            index=models.Index(fields=['-creado'], name='ordenes_ord_creado_a8a6c4_idx'),
        ),
        migrations.AddField(
            model_name='itemorden',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ordenes.orden'),
        ),
        migrations.AddField(
            model_name='itemorden',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_orden', to='shop.producto'),
        ),
    ]
