# Generated by Django 4.1 on 2024-11-10 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Producto',
        ),
        migrations.RenameIndex(
            model_name='producto',
            new_name='shop_produc_id_a6cd00_idx',
            old_name='shop_produc_id_f21274_idx',
        ),
        migrations.RenameIndex(
            model_name='producto',
            new_name='shop_produc_nombre_dc2631_idx',
            old_name='shop_produc_nombre_fe90c6_idx',
        ),
        migrations.RenameIndex(
            model_name='producto',
            new_name='shop_produc_creado_6b0b3c_idx',
            old_name='shop_produc_creado_738c9a_idx',
        ),
    ]
